export const getAllProduct = "GET_ALL_PRODUCTS"
export const getProductById = "GET_PRODUCTS_By_ID"
export const addProducts = "ADD_PRODUCT"
export const deleteProduct = "DELETE_PRODUCT"
export const EditProduct = "EDIT_PRODUCT"
